In [1]:
import openml
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml
import warnings

np.random.seed(42)
warnings.filterwarnings('ignore')


def estimate_features_after_ohe(data_id, task_type='classification', sample_size=None):
    """
    Estimate the number of features after one-hot encoding for an OpenML dataset.
    
    Args:
        data_id: OpenML dataset ID
        task_type: 'classification' or 'regression'
        sample_size: Number of rows to sample for estimation (None = use entire dataset)
        
    Returns:
        Estimated number of features after one-hot encoding
    """
    try:
        dataset = fetch_openml(data_id=data_id, as_frame=True)
        if dataset.target is not None:
            X = dataset.data.copy()
        else:
            if dataset.frame is None:
                return None
            X = dataset.frame.copy()
        
        if X.empty or X.shape[1] == 0:
            return None
        
        # Sample if requested (to speed up estimation)
        if sample_size is not None and len(X) > sample_size:
            X = X.sample(n=min(sample_size, len(X)), random_state=42)
        
        # Count features after one-hot encoding
        # Categorical columns (object type): one feature per unique value
        # Numerical columns: one feature each
        num_features = 0
        for col in X.columns:
            col_dtype = X[col].dtype
            if col_dtype.kind == 'O':  # Object/categorical
                # Count unique values (after one-hot encoding, each unique value becomes a feature)
                n_unique = X[col].nunique()
                num_features += n_unique
            elif col_dtype.name == 'category':  # Pandas category type
                n_unique = X[col].nunique()
                num_features += n_unique
            else:  # Numerical (int, float, bool)
                num_features += 1
        
        return num_features
    except Exception as e:
        return None


def sample_datasets(df, n_samples, random_state=42):
    """
    Perform simple random sampling from a DataFrame.
    
    Args:
        df: DataFrame to sample from (index should contain dataset IDs)
        n_samples: Number of samples to select
        random_state: Random seed
        
    Returns:
        DataFrame with selected samples (preserves original index with dataset IDs)
    """
    if len(df) <= n_samples:
        return df.copy()
    # Sample and preserve the original index (which contains dataset IDs)
    return df.sample(n=n_samples, random_state=random_state)


def compute_max_features_after_ohe(instances, max_complexity=2000000):
    """
    Compute maximum allowed features after OHE based on instance count.
    
    Training time scales roughly with instances × features, so we use a product threshold.
    Small datasets can have more features, large datasets should have fewer.
    
    Args:
        instances: Number of instances in the dataset
        max_complexity: Maximum allowed product (instances × features_after_ohe)
    
    Returns:
        Maximum allowed features after one-hot encoding
    """
    if instances <= 0:
        return 0
    max_features = max_complexity / instances

    return int(max_features)


def select_classification_datasets(n=10, max_instances=50000, max_features=100, 
                                   max_complexity=2000000, random_state=42):
    """
    Select binary classification datasets from CC-18 suite with adaptive filtering.
    
    Uses adaptive filtering: small datasets can have more features after OHE,
    large datasets must have fewer features to keep training time reasonable.
    
    Args:
        n: Number of datasets to select
        max_instances: Maximum number of instances
        max_features: Maximum number of raw features (before one-hot encoding)
        max_complexity: Maximum allowed product (instances × features_after_ohe)
        random_state: Random seed
        
    Returns:
        DataFrame with selected classification datasets, including 'FeaturesAfterOHE' 
        and 'MaxAllowedFeatures' columns
    """
    # Get CC-18 suite
    cc18 = openml.study.get_suite("OpenML-CC18")
    df_cc18 = openml.datasets.list_datasets(data_id=cc18.data, output_format='dataframe')
    
    # Filter: binary classification (2 classes), size constraints
    df_class = df_cc18[
        (df_cc18["NumberOfClasses"] == 2) &
        (df_cc18["NumberOfInstances"] <= max_instances) &
        (df_cc18["NumberOfFeatures"] <= max_features)
    ].copy()
    
    # Estimate features after one-hot encoding for each dataset
    print(f"Estimating features after one-hot encoding for {len(df_class)} datasets...")
    features_after_ohe = []
    max_allowed_features = []
    for i, (idx, row) in enumerate(df_class.iterrows(), 1):
        print(f"  [{i}/{len(df_class)}] Dataset {idx} ({row['name']}): ", end='', flush=True)
        n_features = estimate_features_after_ohe(idx, task_type='classification')
        features_after_ohe.append(n_features)
        
        # Compute max allowed features for this instance count
        n_instances = row['NumberOfInstances']
        max_allowed = compute_max_features_after_ohe(n_instances, max_complexity)
        max_allowed_features.append(max_allowed)
        
        if n_features is not None:
            status = "✅" if n_features <= max_allowed else "❌ (exceeds limit)"
            print(f"{n_features} features after OHE (raw: {row['NumberOfFeatures']}, "
                  f"max allowed: {max_allowed}) {status}")
        else:
            print("failed")
    
    df_class['FeaturesAfterOHE'] = features_after_ohe
    df_class['MaxAllowedFeatures'] = max_allowed_features
    
    # Filter by adaptive threshold: features_after_ohe <= max_allowed for this instance count
    df_class = df_class[
        (df_class['FeaturesAfterOHE'].notna()) &
        (df_class['FeaturesAfterOHE'] <= df_class['MaxAllowedFeatures'])
    ].copy()
    
    print(f"\nAfter adaptive filtering: {len(df_class)} datasets remain")
    if len(df_class) > 0:
        print(f"  Complexity range: {df_class['NumberOfInstances'] * df_class['FeaturesAfterOHE']}")
        print(f"  Min complexity: {(df_class['NumberOfInstances'] * df_class['FeaturesAfterOHE']).min():.0f}")
        print(f"  Max complexity: {(df_class['NumberOfInstances'] * df_class['FeaturesAfterOHE']).max():.0f}")
    
    # Simple random sampling
    return sample_datasets(df_class, n, random_state=random_state)


def select_regression_datasets(n=10, min_instances=1000, max_instances=50000, 
                               max_features=100, max_complexity=2000000, random_state=42):
    """
    Select regression datasets from CTR23 suite with adaptive filtering.
    
    Uses adaptive filtering: small datasets can have more features after OHE,
    large datasets must have fewer features to keep training time reasonable.
    
    Args:
        n: Number of datasets to select
        min_instances: Minimum number of instances
        max_instances: Maximum number of instances
        max_features: Maximum number of raw features (before one-hot encoding)
        max_complexity: Maximum allowed product (instances × features_after_ohe)
        random_state: Random seed
        
    Returns:
        DataFrame with selected regression datasets, including 'FeaturesAfterOHE'
        and 'MaxAllowedFeatures' columns
    """
    # Get CTR23 regression suite
    ctr23 = openml.study.get_suite(353)
    df_ctr23 = openml.datasets.list_datasets(data_id=ctr23.data, output_format='dataframe')
    
    # Filter: size constraints
    df_reg = df_ctr23[
        (df_ctr23["NumberOfInstances"] >= min_instances) &
        (df_ctr23["NumberOfInstances"] <= max_instances) &
        (df_ctr23["NumberOfFeatures"] <= max_features)
    ].copy()
    
    # Estimate features after one-hot encoding for each dataset
    print(f"Estimating features after one-hot encoding for {len(df_reg)} datasets...")
    features_after_ohe = []
    max_allowed_features = []
    for i, (idx, row) in enumerate(df_reg.iterrows(), 1):
        print(f"  [{i}/{len(df_reg)}] Dataset {idx} ({row['name']}): ", end='', flush=True)
        n_features = estimate_features_after_ohe(idx, task_type='regression')
        features_after_ohe.append(n_features)
        
        # Compute max allowed features for this instance count
        n_instances = row['NumberOfInstances']
        max_allowed = compute_max_features_after_ohe(n_instances, max_complexity)
        max_allowed_features.append(max_allowed)
        
        if n_features is not None:
            status = "✅" if n_features <= max_allowed else "❌ (exceeds limit)"
            print(f"{n_features} features after OHE (raw: {row['NumberOfFeatures']}, "
                  f"max allowed: {max_allowed}) {status}")
        else:
            print("failed")
    
    df_reg['FeaturesAfterOHE'] = features_after_ohe
    df_reg['MaxAllowedFeatures'] = max_allowed_features
    
    # Filter by adaptive threshold: features_after_ohe <= max_allowed for this instance count
    df_reg = df_reg[
        (df_reg['FeaturesAfterOHE'].notna()) &
        (df_reg['FeaturesAfterOHE'] <= df_reg['MaxAllowedFeatures'])
    ].copy()
    
    print(f"\nAfter adaptive filtering: {len(df_reg)} datasets remain")
    if len(df_reg) > 0:
        complexity = df_reg['NumberOfInstances'] * df_reg['FeaturesAfterOHE']
        print(f"  Complexity range: {complexity.min():.0f} - {complexity.max():.0f}")
    
    # Simple random sampling
    return sample_datasets(df_reg, n, random_state=random_state)

In [2]:
# Select classification datasets
# max_complexity controls training time: instances × features_after_ohe <= max_complexity
# Lower values = faster training, higher values = allow more complex datasets
classification_datasets = select_classification_datasets(
    n=10, 
    max_features=100,
    max_complexity=100000,
    max_instances=50000,
    random_state=42
)
classification_datasets[["name", "NumberOfInstances", "NumberOfFeatures", "FeaturesAfterOHE", "MaxAllowedFeatures", "NumberOfClasses"]]

Estimating features after one-hot encoding for 30 datasets...
  [1/30] Dataset 3 (kr-vs-kp): 73 features after OHE (raw: 37.0, max allowed: 31) ❌ (exceeds limit)
  [2/30] Dataset 15 (breast-w): 9 features after OHE (raw: 10.0, max allowed: 143) ✅
  [3/30] Dataset 29 (credit-approval): 46 features after OHE (raw: 16.0, max allowed: 144) ✅
  [4/30] Dataset 31 (credit-g): 61 features after OHE (raw: 21.0, max allowed: 100) ✅
  [5/30] Dataset 37 (diabetes): 8 features after OHE (raw: 9.0, max allowed: 130) ✅
  [6/30] Dataset 38 (sick): 53 features after OHE (raw: 30.0, max allowed: 26) ❌ (exceeds limit)
  [7/30] Dataset 44 (spambase): 57 features after OHE (raw: 58.0, max allowed: 21) ❌ (exceeds limit)
  [8/30] Dataset 50 (tic-tac-toe): 27 features after OHE (raw: 10.0, max allowed: 104) ✅
  [9/30] Dataset 151 (electricity): 14 features after OHE (raw: 9.0, max allowed: 2) ❌ (exceeds limit)
  [10/30] Dataset 1049 (pc4): 37 features after OHE (raw: 38.0, max allowed: 68) ✅
  [11/30] Dataset 1050 (pc3): 37 features after OHE (raw: 38.0, max allowed: 63) ✅
  [12/30] Dataset 1053 (jm1): 21 features after OHE (raw: 22.0, max allowed: 9) ❌ (exceeds limit)
  [13/30] Dataset 1063 (kc2): 21 features after OHE (raw: 22.0, max allowed: 191) ✅
  [14/30] Dataset 1067 (kc1): 21 features after OHE (raw: 22.0, max allowed: 47) ✅
  [15/30] Dataset 1068 (pc1): 21 features after OHE (raw: 22.0, max allowed: 90) ✅
  [16/30] Dataset 1461 (bank-marketing): 51 features after OHE (raw: 17.0, max allowed: 2) ❌ (exceeds limit)
  [17/30] Dataset 1462 (banknote-authentication): 4 features after OHE (raw: 5.0, max allowed: 72) ✅
  [18/30] Dataset 1464 (blood-transfusion-service-center): 4 features after OHE (raw: 5.0, max allowed: 133) ✅
  [19/30] Dataset 1480 (ilpd): 11 features after OHE (raw: 11.0, max allowed: 171) ✅
  [20/30] Dataset 1487 (ozone-level-8hr): 72 features after OHE (raw: 73.0, max allowed: 39) ❌ (exceeds limit)
  [21/30] Dataset 1489 (phoneme): 5 features after OHE (raw: 6.0, max allowed: 18) ✅
  [22/30] Dataset 1494 (qsar-biodeg): 41 features after OHE (raw: 42.0, max allowed: 94) ✅
  [23/30] Dataset 1510 (wdbc): 30 features after OHE (raw: 31.0, max allowed: 175) ✅
  [24/30] Dataset 1590 (adult): 105 features after OHE (raw: 15.0, max allowed: 2) ❌ (exceeds limit)
  [25/30] Dataset 4534 (PhishingWebsites): 68 features after OHE (raw: 31.0, max allowed: 9) ❌ (exceeds limit)
  [26/30] Dataset 6332 (cylinder-bands): 162 features after OHE (raw: 40.0, max allowed: 185) ✅
  [27/30] Dataset 23381 (dresses-sales): 156 features after OHE (raw: 13.0, max allowed: 200) ✅
  [28/30] Dataset 40701 (churn): 33 features after OHE (raw: 21.0, max allowed: 20) ❌ (exceeds limit)
  [29/30] Dataset 40983 (wilt): 5 features after OHE (raw: 6.0, max allowed: 20) ✅
  [30/30] Dataset 40994 (climate-model-simulation-crashes): 18 features after OHE (raw: 21.0, max allowed: 185) ✅

After adaptive filtering: 20 datasets remain
  Complexity range: 15        6291.0
29       31740.0
31       61000.0
37        6144.0
50       25866.0
1049     53946.0
1050     57831.0
1063     10962.0
1067     44289.0
1068     23289.0
1462      5488.0
1464      2992.0
1480      6413.0
1489     27020.0
1494     43255.0
1510     17070.0
6332     87480.0
23381    78000.0
40983    24195.0
40994     9720.0
dtype: float64
  Min complexity: 2992
  Max complexity: 87480

,name,NumberOfInstances,NumberOfFeatures,FeaturesAfterOHE,MaxAllowedFeatures,NumberOfClasses
15,breast-w,699.0,10.0,9,143,2.0
23381,dresses-sales,500.0,13.0,156,200,2.0
1510,wdbc,569.0,31.0,30,175,2.0
29,credit-approval,690.0,16.0,46,144,2.0
1067,kc1,2109.0,22.0,21,47,2.0
1049,pc4,1458.0,38.0,37,68,2.0
1464,blood-transfusion-service-center,748.0,5.0,4,133,2.0
37,diabetes,768.0,9.0,8,130,2.0
40983,wilt,4839.0,6.0,5,20,2.0
6332,cylinder-bands,540.0,40.0,162,185,2.0

In [3]:
# Select regression datasets
# max_complexity controls training time: instances × features_after_ohe <= max_complexity
# Lower values = faster training, higher values = allow more complex datasets
regression_datasets = select_regression_datasets(
    n=10, 
    max_features=100,
    max_complexity=100000,
    max_instances=50000,
    random_state=42
)
regression_datasets[["name", "NumberOfInstances", "NumberOfFeatures", "FeaturesAfterOHE", "MaxAllowedFeatures"]]

Estimating features after one-hot encoding for 26 datasets...
  [1/26] Dataset 41021 (Moneyball): 72 features after OHE (raw: 15.0, max allowed: 81) ✅
  [2/26] Dataset 44956 (abalone): 10 features after OHE (raw: 9.0, max allowed: 23) ✅
  [3/26] Dataset 44957 (airfoil_self_noise): 5 features after OHE (raw: 6.0, max allowed: 66) ✅
  [4/26] Dataset 44958 (auction_verification): 16 features after OHE (raw: 8.0, max allowed: 48) ✅
  [5/26] Dataset 44959 (concrete_compressive_strength): 8 features after OHE (raw: 9.0, max allowed: 97) ✅
  [6/26] Dataset 44963 (physiochemical_protein): 9 features after OHE (raw: 10.0, max allowed: 2) ❌ (exceeds limit)
  [7/26] Dataset 44964 (superconductivity): 81 features after OHE (raw: 82.0, max allowed: 4) ❌ (exceeds limit)
  [8/26] Dataset 44966 (solar_flare): 29 features after OHE (raw: 11.0, max allowed: 93) ✅
  [9/26] Dataset 44969 (naval_propulsion_plant): 14 features after OHE (raw: 15.0, max allowed: 8) ❌ (exceeds limit)
  [10/26] Dataset 44971 (white_wine): 11 features after OHE (raw: 12.0, max allowed: 20) ✅
  [11/26] Dataset 44972 (red_wine): 11 features after OHE (raw: 12.0, max allowed: 62) ✅
  [12/26] Dataset 44973 (grid_stability): 12 features after OHE (raw: 13.0, max allowed: 10) ❌ (exceeds limit)
  [13/26] Dataset 44976 (sarcos): 21 features after OHE (raw: 22.0, max allowed: 2) ❌ (exceeds limit)
  [14/26] Dataset 44977 (california_housing): 8 features after OHE (raw: 9.0, max allowed: 4) ❌ (exceeds limit)
  [15/26] Dataset 44978 (cpu_activity): 21 features after OHE (raw: 22.0, max allowed: 12) ❌ (exceeds limit)
  [16/26] Dataset 44980 (kin8nm): 8 features after OHE (raw: 9.0, max allowed: 12) ✅
  [17/26] Dataset 44981 (pumadyn32nh): 32 features after OHE (raw: 33.0, max allowed: 12) ❌ (exceeds limit)
  [18/26] Dataset 44983 (miami_housing): 15 features after OHE (raw: 16.0, max allowed: 7) ❌ (exceeds limit)
  [19/26] Dataset 44984 (cps88wages): 12 features after OHE (raw: 7.0, max allowed: 3) ❌ (exceeds limit)
  [20/26] Dataset 44987 (socmob): 39 features after OHE (raw: 6.0, max allowed: 86) ✅
  [21/26] Dataset 44989 (kings_county): 132 features after OHE (raw: 22.0, max allowed: 4) ❌ (exceeds limit)
  [22/26] Dataset 44990 (brazilian_houses): 49 features after OHE (raw: 10.0, max allowed: 9) ❌ (exceeds limit)
  [23/26] Dataset 44992 (fps_benchmark): 126 features after OHE (raw: 44.0, max allowed: 4) ❌ (exceeds limit)
  [24/26] Dataset 44993 (health_insurance): 25 features after OHE (raw: 12.0, max allowed: 4) ❌ (exceeds limit)
  [25/26] Dataset 45012 (fifa): 190 features after OHE (raw: 29.0, max allowed: 5) ❌ (exceeds limit)
  [26/26] Dataset 45402 (space_ga): 6 features after OHE (raw: 7.0, max allowed: 32) ✅

After adaptive filtering: 11 datasets remain
  Complexity range: 7515 - 88704

,name,NumberOfInstances,NumberOfFeatures,FeaturesAfterOHE,MaxAllowedFeatures
44966,solar_flare,1066.0,11.0,29,93
41021,Moneyball,1232.0,15.0,72,81
44987,socmob,1156.0,6.0,39,86
45402,space_ga,3107.0,7.0,6,32
44957,airfoil_self_noise,1503.0,6.0,5,66
44956,abalone,4177.0,9.0,10,23
44980,kin8nm,8192.0,9.0,8,12
44959,concrete_compressive_strength,1030.0,9.0,8,97
44972,red_wine,1599.0,12.0,11,62
44958,auction_verification,2043.0,8.0,16,48

In [4]:
# Test timing for one split per dataset
import subprocess
import time
import tempfile
import os
import shutil
from pathlib import Path
from hp_tuning_utils import load_hp_tuning_conf

# Get dataset IDs
classification_ids = classification_datasets.index.tolist()
regression_ids = regression_datasets.index.tolist()

# Default hyperparameters for timing test
default_hp = {
    'dropout': 0.2,
    'l2_regularization': 1e-5,
    'learning_rate': 0.01,
    'feature_dropout': 0.05,
    'output_regularization': 0.05
}

# Load configs
class_config = Path('hp_tuning_conf/openml_classification.json')
reg_config = Path('hp_tuning_conf/openml_regression.json')
_, class_fixed = load_hp_tuning_conf(class_config)
_, reg_fixed = load_hp_tuning_conf(reg_config)

def run_timing_test(dataset_id, task_type, timeout_s=3600):
    """Run one split and measure time."""
    dataset_name = f"OpenML_{dataset_id}_{task_type}"
    fixed_hp = (class_fixed if task_type == 'classification' else reg_fixed).copy()
    fixed_hp['dataset_name'] = dataset_name
    fixed_hp['regression'] = (task_type == 'regression')
    
    # Temp logdir
    temp_logdir = os.path.join(tempfile.gettempdir(), f'nam_timing_{dataset_id}')
    os.makedirs(temp_logdir, exist_ok=True)
    
    # Build command
    all_hp = {**fixed_hp, **default_hp}
    all_hp['logdir'] = os.path.join(temp_logdir, 'trial_1')
    all_hp['data_split'] = 1
    
    cmd = ['python', '-m', 'neural_additive_models.nam_train']
    for k, v in all_hp.items():
        if v is None:
            cmd.append(f'--{k}=None')
        elif isinstance(v, bool):
            cmd.append(f'--{k}={"true" if v else "false"}')
        else:
            cmd.append(f'--{k}={v}')
    
    # Run
    print(f"{dataset_name:40s}...", end=' ', flush=True)
    start = time.time()
    try:
        result = subprocess.run(' '.join(cmd), shell=True, capture_output=True, 
                               text=True, timeout=timeout_s)
        elapsed = time.time() - start
        success = result.returncode == 0
        print(f"{'✅' if success else '❌'} {elapsed:.1f}s")
        return {'dataset_id': dataset_id, 'name': dataset_name, 'task': task_type,
                'time': elapsed, 'success': success}
    except subprocess.TimeoutExpired:
        elapsed = time.time() - start
        print(f"⏱️ {elapsed:.1f}s (timeout)")
        return {'dataset_id': dataset_id, 'name': dataset_name, 'task': task_type,
                'time': elapsed, 'success': False}
    finally:
        shutil.rmtree(temp_logdir, ignore_errors=True)

# Run tests
print("="*70)
print("TIMING TESTS - One Split Per Dataset")
print("="*70)

results = []
print("\nClassification:")
for did in classification_ids:
    results.append(run_timing_test(did, 'classification'))

print("\nRegression:")
for did in regression_ids:
    results.append(run_timing_test(did, 'regression'))

# Summary
print("\n" + "="*70)
print("SUMMARY")
print("="*70)
df = pd.DataFrame(results)
print(df[['name', 'time', 'success']].to_string(index=False))
print(f"\nTotal time: {df['time'].sum():.1f}s")
print(f"Average: {df['time'].mean():.1f}s")
print(f"Successful: {df['success'].sum()}/{len(df)}")

WARNING:tensorflow:From c:\Users\dejvi\Documents\pythonProject\neural-additive-models-xai-seminar-1\venv_nam\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

======================================================================
TIMING TESTS - One Split Per Dataset
======================================================================

Classification:
OpenML_15_classification                ... ✅ 16.7s
OpenML_23381_classification             ... ✅ 200.3s
OpenML_1510_classification              ... ✅ 43.8s
OpenML_29_classification                ... ✅ 57.5s
OpenML_1067_classification              ... ✅ 37.1s
OpenML_1049_classification              ... ✅ 174.2s
OpenML_1464_classification              ... ✅ 15.0s
OpenML_37_classification                ... ✅ 21.4s
OpenML_40983_classification             ... ✅ 30.2s
OpenML_6332_classification              ... ✅ 329.4s

Regression:
OpenML_44966_regression                 ... ✅ 70.6s
OpenML_41021_regression                 ... ✅ 162.9s
OpenML_44987_regression                 ... ✅ 68.8s
OpenML_45402_regression                 ... ✅ 74.9s
OpenML_44957_regression                 ... ✅ 26.3s
OpenML_44956_regression                 ... ✅ 48.7s
OpenML_44980_regression                 ... ✅ 98.0s
OpenML_44959_regression                 ... ✅ 36.5s
OpenML_44972_regression                 ... ✅ 31.8s
OpenML_44958_regression                 ... ✅ 112.4s

======================================================================
SUMMARY
======================================================================
                       name       time  success
   OpenML_15_classification  16.653746     True
OpenML_23381_classification 200.264012     True
 OpenML_1510_classification  43.774465     True
   OpenML_29_classification  57.466610     True
 OpenML_1067_classification  37.081942     True
 OpenML_1049_classification 174.176868     True
 OpenML_1464_classification  15.049750     True
   OpenML_37_classification  21.382922     True
OpenML_40983_classification  30.218563     True
 OpenML_6332_classification 329.378752     True
    OpenML_44966_regression  70.638277     True
    OpenML_41021_regression 162.909766     True
    OpenML_44987_regression  68.809638     True
    OpenML_45402_regression  74.946392     True
    OpenML_44957_regression  26.330420     True
    OpenML_44956_regression  48.738195     True
    OpenML_44980_regression  98.041117     True
    OpenML_44959_regression  36.504098     True
    OpenML_44972_regression  31.768908     True
    OpenML_44958_regression 112.434109     True

Total time: 1656.6s
Average: 82.8s
Successful: 20/20